# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/rentaldb
spring.datasource.username=root
spring.datasource.password=2005

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Thymeleaf Settings
spring.thymeleaf.cache=false

# App Port
server.port=${PORT:8080}
server.address=0.0.0.0

# App Name
spring.application.name=OnlineRentalSystem
spring.web.resources.cache.period=0
spring.thymeleaf.cache=false

# Email Configuration
 sendgrid.api.key=${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}