# Database Connection
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/rentaldb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:2005}

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Thymeleaf Settings
spring.thymeleaf.cache=false

# App Port
server.port=${PORT:8080}
server.address=0.0.0.0

# App Name
spring.application.name=OnlineRentalSystem
spring.web.resources.cache.period=0

# Brevo Email
brevo.api.key=${BREVO_API_KEY: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 }
